# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('products', '0001_initial'), ('products', '0002_remove_product_item_id'), ('products', '0003_auto_20160202_1801')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(default='This is the default description. Be sure to change it later!')),
                ('price', models.DecimalField(decimal_places=2, default=9.99, max_digits=100)),
            ],
        ),
    ]
