# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_squashed_0003_auto_20160202_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
    ]
